name: scheduled castles collecting and enrichment

on:
  schedule:
    - cron: '*/2 * * * *' #'0 0 * * 1'  # every Monday at 00:00 GMT-0

jobs:
  enrich:
    runs-on: ubuntu-latest
    steps:
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: go get
      run: go get all

    - name: run enricher
      env:
        DB_URI: ${{ secrets.DB_URI }}
        ENRICHMENT_TIMEOUT_IN_SECONDS: ${{ secrets.ENRICHMENT_TIMEOUT_IN_SECONDS }}
      run: go run cmd/enricher/*.go
