name: scheduled castles collecting and enrichment

on:
  schedule:
    - cron: '0 15 * * *'  # daily at 15:00 GMT-0

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run enricher
        env:
          DB_URI: ${{ secrets.DB_URI }}
          ENRICHMENT_TIMEOUT_IN_SECONDS: ${{ secrets.ENRICHMENT_TIMEOUT_IN_SECONDS }}
        run: go run cmd/enricher/*.go
