name: tests

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: verify dependencies
      run: go mod verify

    - name: build
      run: go build cmd/

    - name: run go vet
      run: go vet ./...

    - name: install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: run staticcheck
      run: staticcheck ./...

    - name: run tests
      run: go test -race -vet=off ./...
